apiVersion: apps/v1
kind: Deployment
metadata:
  name: alamae-assignment3-deployment
  labels:
    app: alamae-assignment3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alamae-assignment3
  template:
    metadata:
      labels:
        app: alamae-assignment3
    spec:
      containers:
      - name: alamae-assignment3
        image: alamae-assignment3:latest 
        imagePullPolicy: IfNotPresent
